on: push
name: Test Buildkit Gem

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run rspec
        run: 'bundle exec rspec spec'
